name: companion
description: App for route companion
version: 1.1.2+45

publish_to: none

environment:
  sdk: ">=3.0.0<=4.0.0"
  flutter: 3.0.5

dependencies:
  cached_network_image: ^3.2.2
  # carousel_slider: ^4.2.1
  dio: ^5.2.1+1
  drift: ^2.15.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^8.0.0
  flutter_svg: ^2.0.2
  freezed_annotation: ^2.4.1
  go_router: ^8.0.5
  intl: ^0.19.0
  json_annotation: ^4.9.0
  l: ^4.0.1
  mask_text_input_formatter: ^2.4.0
  path: ^1.8.2
  path_provider: ^2.0.11
  platform_info: ^4.0.0
  pure: ^0.2.0
  companion_api:
    path: packages/companion_api
  yandex_maps_api:
    path: packages/yandex_maps_api
  sentry_flutter: ^8.9.0
  shared_preferences: ^2.0.15
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.0.1
  sqlite3_flutter_libs: ^0.5.23
  stack_trace: ^1.11.0
  stream_transform: ^2.0.1
  url_launcher: ^6.3.0
  yandex_mapkit_lite: ^2.0.2
  yandex_geocoder: ^2.3.1
  google_nav_bar: ^5.0.6
  pinput: ^4.0.0
  render_metrics: ^2.0.2
  flutter_rating_bar: ^4.0.1
  equatable: ^2.0.5
  permission_handler: ^11.3.1
  location: ^6.0.2
  geolocator: ^11.1.0
  throttling: ^2.0.1
  scroll_datetime_picker: ^0.1.0
  fluttertoast: ^8.2.5
  firebase_core: ^3.1.1
  firebase_messaging: ^15.0.2
  flutter_local_notifications: ^17.2.1
  flutter_chat_ui: ^1.6.14
  flutter_chat_types: ^3.6.2
  bubble: ^1.2.1
  scroll_to_index: ^3.0.1
  collection: ^1.18.0
  flutter_app_badger: ^1.5.0
  map_launcher: ^3.5.0

dev_dependencies:
  build_runner: ^2.3.3
  drift_dev: ^2.15.0
  flutter_gen_runner: ^5.2.0
  flutter_native_splash: ^2.2.19
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  select: ^0.4.1
  very_good_analysis: ^5.1.0

flutter_gen:
  # Optional
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: SofiaPro
      fonts:
        - asset: fonts/SofiaPro/SofiaProRegular.ttf
          weight: 400
        - asset: fonts/SofiaPro/SofiaProMedium.ttf
          weight: 500
        - asset: fonts/SofiaPro/SofiaProSemiBold.ttf
          weight: 600
        - asset: fonts/SofiaPro/SofiaProBold.ttf
          weight: 700
        - asset: fonts/SofiaPro/SofiaProBlack.ttf
          weight: 900
    - family: NunitoSans
      fonts:
        - asset: fonts/NunitoSans/NunitoSans-Light.ttf
          weight: 300
        - asset: fonts/NunitoSans/NunitoSans-Regular.ttf
          weight: 400
        - asset: fonts/NunitoSans/NunitoSans-SemiBold.ttf
          weight: 600
        - asset: fonts/NunitoSans/NunitoSans-Bold.ttf
          weight: 700
        - asset: fonts/NunitoSans/NunitoSans-ExtraBold.ttf
          weight: 800
        - asset: fonts/NunitoSans/NunitoSans-Black.ttf
          weight: 900
    - family: Nunito
      fonts:
        - asset: fonts/Nunito/Nunito-Light.ttf
          weight: 300
        - asset: fonts/Nunito/Nunito-Regular.ttf
          weight: 400
        - asset: fonts/Nunito/Nunito-Medium.ttf
          weight: 500
        - asset: fonts/Nunito/Nunito-SemiBold.ttf
          weight: 600
        - asset: fonts/Nunito/Nunito-Bold.ttf
          weight: 700
        - asset: fonts/Nunito/Nunito-ExtraBold.ttf
          weight: 800
        - asset: fonts/Nunito/Nunito-Black.ttf
          weight: 900
