name: companion_api
description: A Dart API REST Client for traveling companion app.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0<=4.0.0"

dependencies:
  dio: ^5.2.1+1
  equatable: ^2.0.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  retrofit: ^4.0.1

dev_dependencies:
  build_runner: ^2.2.1
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  retrofit_generator: ^7.0.7
  test: ^1.24.9
  very_good_analysis: ^5.1.0
